### ISSUE TITLE
How do we explain security around API keys?

### ISSUE THREAD

**Issue by nduckwiler** [JohnPhamous/codecademy-daily-journal#5]
@JohnPhamous you may have explained this before so sorry in advance.

When I use your app at https://goofy-hopper-a9bd1f.netlify.app/, I can monitor network requests and find your API keys. **What should we recommend our learners to do?** I'm not sure if they should set something up with Netlify, use the .env.sample file, or something else.

Whatever the implementation, I _think_ we'll say that this is not a good convention, but you can do it now for the sake of practice. We can then add Authentication as one of the "Next Steps".

https://github.com/JohnPhamous/codecademy-daily-journal/blob/035902dc31d18b7eac02f1bb86167fde6937d307/src/api/openWeatherMap/index.js#L1

**Comment by JohnPhamous** [comment]
@nduckwiler I'm treating this project like a hackathon project. 

- Yes, exposing API keys is a bad practice. Doing it the correct way where we don't expose the API keys will require a backend to act as a proxy.
   - UI ---GET myapi/weather---> MyAPI ---GET weatherApi/weather---> MyAPI ---> UI

We should stress:

1. Secrets should not be version controlled (hence `.env` being ignored by git and `.env.sample` that is versioned
2. This is a frontend focused project and there are security limitations because of that

**Comment by nduckwiler** [comment]
This all sounds good to me. Your explanation can go in "Long Overview" section of the project.
